export const blogData = [
  {
    id: "1",
    title: "Travel to the great beyond and never stop!",
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    featureImage: "/assets/post1.jpg",
    tags: ["Adventure"],
    author: "Antonio Rogers",
    publishDate: "September 27, 2023",
    attraction: undefined,
    tour: undefined,
  },
  {
    id: "2",
    title: "Wanderlust Chronicles: Tales of a Nomadic Soul",
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    featureImage: "/assets/post2.jpg",
    tags: ["Culture"],
    author: "Antonio Rogers",
    publishDate: "September 27, 2023",
    attraction: undefined,
    tour: undefined,
  },
  {
    id: "3",
    title: "Wander Without Borders: Exploring Boundless Beauty",
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    featureImage: "/assets/post3.jpg",
    tags: ["Discovery"],
    author: "Antonio Rogers",
    publishDate: "September 27, 2023",
    attraction: undefined,
    tour: undefined,
  },
  {
    id: "4",
    title: "Off the Map Adventures: Chasing the Unknown",
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    featureImage: "/assets/post4.jpg",
    tags: ["Journeys"],
    author: "Antonio Rogers",
    publishDate: "September 27, 2023",
    attraction: undefined,
    tour: undefined,
  },
  {
    id: "5",
    title: "Roaming with Purpose: Life on the Road",
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    featureImage: "/assets/post5.jpg",
    tags: ["Adventure"],
    author: "Antonio Rogers",
    publishDate: "September 1, 2023",
    attraction: undefined,
    tour: undefined,
  },
  {
    id: "6",
    title: "Footprints Across Continents: The Traveler's Tale",
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    featureImage: "/assets/post6.jpg",
    tags: ["Wanderlust"],
    author: "Antonio Rogers",
    publishDate: "September 27, 2023",
    attraction: undefined,
    tour: undefined,
  },
  {
    id: "7",
    title: "Travel to the great beyond and never stop!",
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    featureImage: "/assets/post7.jpg",
    tags: ["Adventure"],
    author: "Antonio Rogers",
    publishDate: "September 27, 2023",
    attraction: undefined,
    tour: undefined,
  },
  {
    id: "8",
    title: "Travel to the great beyond and never stop!",
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    featureImage: "/assets/post8.jpg",
    tags: ["Odyssey"],
    author: "Antonio Rogers",
    publishDate: "September 27, 2023",
    attraction: undefined,
    tour: undefined,
  },
  {
    id: "9",
    title: "Travel to the great beyond and never stop!",
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    featureImage: "/assets/post9.jpg",
    tags: ["Exploration"],
    author: "Antonio Rogers",
    publishDate: "September 22, 2023",
    attraction: undefined,
    tour: undefined,
  },
  {
    id: "10",
    title: "Travel to the great beyond and never stop!",
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    featureImage: "/assets/post9.jpg",
    tags: ["Exploration"],
    author: "Antonio Rogers",
    publishDate: "September 29, 2023",
    attraction: undefined,
    tour: undefined,
  },
];
